function interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)

% obiecte de interfata grafica
fig =figure('Name','Circuit de Insumare',...
    'Units','normalized',...
    'Position',[0.1 0.1 0.7 0.8],...
    'NumberTitle','off',...
    'Color','[0.3010, 0.7450, 0.9330]');


RadioGroupAO=uibuttongroup('Visible','on',...
    'BackgroundColor','[0.3010, 0.7450, 0.9330]',...
    'ForegroundColor','black',...
    'Title','Limitari AO:',...
    'FontSize',13,...
    'FontWeight','bold',...
    'TitlePosition','centertop',...
    'Tag','radiobutton',...
    'BorderWidth',2,...
    'FontAngle','italic',...
    'HighlightColor','[0.9290, 0.6940, 0.1250]',...
    'Position',[0.75 0.13 0.2 0.3]);

vAl = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.15 0.65 0.15 .1],...
    'FontSize',13,...
    'FontAngle','italic',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'String','Vcc',...
    'Parent',RadioGroupAO);

eq = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.38 0.65 0.1 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','=',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Parent',RadioGroupAO);

Vcc = uicontrol("Style","edit",...
    'Units','normalized',...
    'Position',[0.55 0.65 0.2 .1],...
    'FontAngle','italic',...
    'FontSize',11,...
    'String',VAlim,...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Callback',['VAlim=','str2num(get(gco,''String''));close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)'],...
    'Parent',RadioGroupAO);

volt = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.8 0.65 0.1 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','V',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Parent',RadioGroupAO);

SrT = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.05 0.45 0.25 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'String','Slew Rate',...
    'Parent',RadioGroupAO);

eq = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.38 0.45 0.1 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','=',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Parent',RadioGroupAO);

Sr = uicontrol("Style","edit",...
    'Units','normalized',...
    'Position',[0.55 0.45 0.2 .1],...
    'FontAngle','italic',...
    'FontSize',11,...
    'String',SR,...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Callback',['SR=','str2num(get(gco,''String''));close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)'],...
    'Parent',RadioGroupAO);

muSR = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.8 0.45 0.15 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','V/µS',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Parent',RadioGroupAO);

iT = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.1 0.25 0.2 .1],...
    'FontSize',11,...
    'FontAngle','italic',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'String','Iomax',...
    'Parent',RadioGroupAO);

eq = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.38 0.25 0.1 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','=',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Parent',RadioGroupAO);

i_max = uicontrol("Style","edit",...
    'Units','normalized',...
    'Position',[0.55 0.25 0.2 .1],...
    'FontAngle','italic',...
    'FontSize',11,...
    'String',IMAX,...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Callback',['IMAX=','str2num(get(gco,''String''));close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)'],...
    'Parent',RadioGroupAO);

muImax = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.8 0.25 0.1 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','mA',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Parent',RadioGroupAO);


in1 = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.16 0.9 0.15 .03],...
    'FontSize',10,...
    'FontWeight','bold',...
    'String','Semnal de intrare I:',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]');

tip1 = uicontrol('Style','PopupMenu',...
    'Units','normalized',...
    'Position',[0.32 0.89 0.09 0.04],...
    'String',"Continuu|Sinus|Dreptunghiular|Triunghiular",...
    'Value',type1,...
    'FontSize',10,...
    'FontAngle','italic',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Callback',['type1=','get(gco,''Value'');close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)']);

vmedtext = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.12 0.83 0.05 .03],...
    'FontSize',11,...
    'FontAngle','italic',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'String','Vmed [V]');

vMed1 = uicontrol("Style","edit",...
    'Units','normalized',...
    'Position',[0.18 0.83 0.04 .03],...
    'FontAngle','italic',...
    'FontSize',11,...
    'String',ValMed1,...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Callback',['ValMed1=','str2num(get(gco,''String''));close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)']);


if type1 == 2 || type1 == 3 || type1 ==4

    ampltext = uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.23 0.83 0.05 .03],...
        'FontSize',11,...
        'FontAngle','italic',...
        'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
        'String','Ampl [V]');

    ampl1 = uicontrol("Style","edit",...
        'Units','normalized',...
        'Position',[0.29 0.83 0.04 .03],...
        'FontAngle','italic',...
        'FontSize',11,...
        'String',Ampl1,...
        'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
        'Callback',['Ampl1=','str2num(get(gco,''String''));close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)']);

    frecvltext = uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.34 0.83 0.06 .03],...
        'FontSize',11,...
        'FontAngle','italic',...
        'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
        'String','Frecv [Hz]');

    fr1 = uicontrol("Style","edit",...
        'Units','normalized',...
        'Position',[0.41 0.83 0.06 .03],...
        'FontAngle','italic',...
        'FontSize',11,...
        'String',f1,...
        'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
        'Callback',['f1=','str2num(get(gco,''String''));close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)']);

end


in2 = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.16 0.75 0.15 .03],...
    'FontSize',10,...
    'FontWeight','bold',...
    'String','Semnal de intrare II:',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]');

tip2 = uicontrol('Style','PopupMenu',...
    'Units','normalized',...
    'Position',[0.32 0.74 0.09 0.04],...
    'String',"Continuu|Sinus|Dreptunghiular|Triunghiular",...
    'Value',type2,...
    'FontSize',10,...
    'FontAngle','italic',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Callback',['type2=','get(gco,''Value'');close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)']);

vmedtext = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.12 0.68 0.05 .03],...
    'FontSize',11,...
    'FontAngle','italic',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'String','Vmed [V]');

vMed2 = uicontrol("Style","edit",...
    'Units','normalized',...
    'Position',[0.18 0.68 0.04 .03],...
    'FontAngle','italic',...
    'FontSize',11,...
    'String',ValMed2,...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Callback',['ValMed2=','str2num(get(gco,''String''));close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)']);


if type2 == 2 || type2 == 3 || type2 == 4
    ampltext = uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.23 0.68 0.05 .03],...
        'FontSize',11,...
        'FontAngle','italic',...
        'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
        'String','Ampl [V]');

    ampl2 = uicontrol("Style","edit",...
        'Units','normalized',...
        'Position',[0.29 0.68 0.04 .03],...
        'FontAngle','italic',...
        'FontSize',11,...
        'String',Ampl2,...
        'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
        'Callback',['Ampl2=','str2num(get(gco,''String''));close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)']);

    frecvltext = uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.34 0.68 0.06 .03],...
        'FontSize',11,...
        'FontAngle','italic',...
        'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
        'String','Frecv [Hz]');

    fr2 = uicontrol("Style","edit",...
        'Units','normalized',...
        'Position',[0.41 0.68 0.06 .03],...
        'FontAngle','italic',...
        'FontSize',11,...
        'String',f2,...
        'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
        'Callback',['f2=','str2num(get(gco,''String''));close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)']);

end

RadioGroup=uibuttongroup('Visible','on',...
    'BackgroundColor','[0.3010, 0.7450, 0.9330]',...
    'ForegroundColor','black',...
    'Title','Rezistente:',...
    'FontSize',13,...
    'FontWeight','bold',...
    'TitlePosition','centertop',...
    'Tag','radiobutton',...
    'BorderWidth',2,...
    'FontAngle','italic',...
    'HighlightColor','[0.9290, 0.6940, 0.1250]',...
    'Position',[0.55 0.13 0.2 0.3]);

rnT = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.15 0.75 0.15 .1],...
    'FontSize',12,...
    'FontAngle','italic',...
    'String','Rn',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Parent',RadioGroup);

eq = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.38 0.75 0.1 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','=',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Parent',RadioGroup);

rn = uicontrol("Style","edit",...
    'Units','normalized',...
    'Position',[0.55 0.75 0.2 .1],...
    'FontAngle','italic',...
    'FontSize',11,...
    'String',Rn,...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Callback',['Rn=','str2num(get(gco,''String''));close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)'],...
    'Parent',RadioGroup);

xRnPop = uicontrol('Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.8 0.75 0.17 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','Ω|kΩ|MΩ',...
    'Value',xRn,...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Callback',['xRn=','get(gco,''Value'');close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)'],...
    'Parent',RadioGroup);

r1T = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.15 0.55 0.15 .1],...
    'FontSize',12,...
    'FontAngle','italic',...
    'String','R1',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Parent',RadioGroup);

eq = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.38 0.55 0.1 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','=',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Parent',RadioGroup);

r1 = uicontrol("Style","edit",...
    'Units','normalized',...
    'Position',[0.55 0.55 0.2 .1],...
    'FontAngle','italic',...
    'FontSize',11,...
    'String',R1,...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Callback',['R1=','str2num(get(gco,''String''));close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)'],...
    'Parent',RadioGroup);

xR1Pop = uicontrol('Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.8 0.55 0.17 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','Ω|kΩ|MΩ',...
    'Value',xR1,...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Callback',['xR1=','get(gco,''Value'');close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)'],...
    'Parent',RadioGroup);

r2T = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.15 0.35 0.15 .1],...
    'FontSize',12,...
    'FontAngle','italic',...
    'String','R2',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Parent',RadioGroup);

eq = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.38 0.35 0.1 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','=',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Parent',RadioGroup);


r2 = uicontrol("Style","edit",...
    'Units','normalized',...
    'Position',[0.55 0.35 0.2 .1],...
    'FontAngle','italic',...
    'FontSize',11,...
    'String',R2,...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Callback',['R2=','str2num(get(gco,''String''));close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)'],...
    'Parent',RadioGroup);

xR2Pop = uicontrol('Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.8 0.35 0.17 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','Ω|kΩ|MΩ',...
    'Value',xR2,...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Callback',['xR2=','get(gco,''Value'');close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)'],...
    'Parent',RadioGroup);

r3T = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.15 0.15 0.15 .1],...
    'FontSize',12,...
    'FontAngle','italic',...
    'String','R3',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Parent',RadioGroup);

eq = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.38 0.15 0.1 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','=',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Parent',RadioGroup);

r3 = uicontrol("Style","edit",...
    'Units','normalized',...
    'Position',[0.55 0.15 0.2 .1],...
    'FontAngle','italic',...
    'FontSize',11,...
    'String',R3,...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Callback',['R3=','str2num(get(gco,''String''));close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)'],...
    'Parent',RadioGroup);

xR3Pop = uicontrol('Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.8 0.15 0.17 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','Ω|kΩ|MΩ',...
    'Value',xR3,...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Callback',['xR3=','get(gco,''Value'');close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)'],...
    'Parent',RadioGroup);

in3 = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.16 0.6 0.15 .03],...
    'FontSize',10,...
    'FontWeight','bold',...
    'String','Semnal de intrare III:',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]');


tip3 = uicontrol('Style','PopupMenu',...
    'Units','normalized',...
    'Position',[0.32 0.59 0.09 0.04],...
    'String',"Continuu|Sinus|Dreptunghiular|Triunghiular",...
    'Value',type3,...
    'FontSize',10,...
    'FontAngle','italic',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Callback',['type3=','get(gco,''Value'');close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)']);

vmedtext = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.12 0.53 0.05 .03],...
    'FontSize',11,...
    'FontAngle','italic',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'String','Vmed [V]');

vMed3 = uicontrol("Style","edit",...
    'Units','normalized',...
    'Position',[0.18 0.53 0.04 .03],...
    'FontAngle','italic',...
    'FontSize',11,...
    'String',ValMed3,...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Callback',['ValMed3=','str2num(get(gco,''String''));close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)']);


if type3 == 2 || type3 == 3 || type3 == 4

    ampltext = uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.23 0.53 0.05 .03],...
        'FontSize',11,...
        'FontAngle','italic',...
        'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
        'String','Ampl [V]');

    ampl3 = uicontrol("Style","edit",...
        'Units','normalized',...
        'Position',[0.29 0.53 0.04 .03],...
        'FontAngle','italic',...
        'FontSize',11,...
        'String',Ampl3,...
        'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
        'Callback',['Ampl3=','str2num(get(gco,''String''));close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)']);

    frecvltext = uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.34 0.53 0.06 .03],...
        'FontSize',11,...
        'FontAngle','italic',...
        'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
        'String','Frecv [Hz]');

    fr3 = uicontrol("Style","edit",...
        'Units','normalized',...
        'Position',[0.41 0.53 0.06 .03],...
        'FontAngle','italic',...
        'FontSize',11,...
        'String',f3,...
        'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
        'Callback',['f3=','str2num(get(gco,''String''));close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)']);

end


%Buton reset
uicontrol("Style","pushbutton",...
    "Units","normalized",...
    'Position',[0.7 0.05 0.1 .05],...
    'FontAngle','italic',...
    'FontSize',11,...
    'String','Resetare',...
    'BackgroundColor','[0.9290, 0.6940, 0.1250]',...
    'Callback',['f1=1000; f2=1000; f3 = 1000;ValMed1=0; ValMed2= 0;ValMed3=0;Ampl1=0;Ampl2=0;Ampl3=0;R1=470;R2=470;R3=470;Rn=470;xR1=1;xR2=1;xR3=1;xRn=1;type1=2;type2=2;type3=2;VAlim=20;IMAX=20;SR=4.3;close;interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn)']);


% Standardizarea Valorilor rezistentelor

multn = multiply(xRn);
mult1 = multiply(xR1);
mult2 = multiply(xR2);
mult3 = multiply(xR3);

newRn = rezistenteSTD(xRn,Rn);
if newRn ~= 0
    Rn = newRn;
    close;
    interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn);
end

newR1 = rezistenteSTD(xR1,R1);
if newR1 ~= 0       % daca valoarea rezistentei nu e standarda
    R1 = newR1;     % rezistenta va fi actualizata automat
    close;
    interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn);
end

newR2 = rezistenteSTD(xR2,R2);
if newR2 ~= 0
    R2 = newR2;
    close;
    interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn);
end

newR3 = rezistenteSTD(xR3,R3);
if newR3 ~= 0
    R3 = newR3;
    close;
    interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn);
end




% Afisarea schemei de circuit

grid on;
Sumator_3 = imread('c3.PNG');
subplot(222)
image(Sumator_3)
title('Schema circuitului','FontAngle','italic','FontSize',15)
axis off
axis image

% Calculul si expresiile pentru semnalele de intrare

T1= 1/f1;
T2 = 1/f2;
T3 = 1/f3;
T= max([T1,T2,T3]);
t=0:T/100:2*T;

switch type1
    case 1
        if ValMed1 > VAlim
            ValMed1 = VAlim;
        elseif ValMed1 < - VAlim
            ValMed1 = -VAlim;
        end

        s1 = ValMed1;
        % semnal continuu
    case 2
        s1 = ValMed1 + Ampl1*sin(2*pi*t/T1);    % semnal sinusoidal
    case 3
        s1 = ValMed1 + Ampl1*square(2*pi*t/T1,50);  % semnal dreptunghiular
    case 4
        s1 = ValMed1 + Ampl1*sawtooth(2*pi*t/T1+pi/2,0.5);  % semnal triunghiular
end

switch type2
    case 1
        if ValMed2 > VAlim
            ValMed2 = VAlim;
        elseif ValMed2 < - VAlim
            ValMed2 = -VAlim;
        end

        s2 = ValMed2;

    case 2
        s2 = ValMed2 + Ampl2*sin(2*pi*t/T2);
    case 3
        s2 = ValMed2 + Ampl2*square(2*pi*t/T2,50);
    case 4
        s2 = ValMed2 + Ampl2*sawtooth(2*pi*t/T2+pi/2,0.5);
end

switch type3
    case 1
        if ValMed3 > VAlim
            ValMed3 = VAlim;
        elseif ValMed3 < - VAlim
            ValMed3 = -VAlim;
        end

        s3 = ValMed3;

    case 2
        s3 = ValMed3 + Ampl3*sin(2*pi*t/T3);
    case 3
        s3 = ValMed3 + Ampl3*square(2*pi*t/T3,50);
    case 4
        s3 = ValMed3 + Ampl3*sawtooth(2*pi*t/T3+pi/2,0.5);
end




% Limitarea valorilor semnalelor de intrare si iesire la valoarea de
% alimentare

Vmax1 = 0;
Vmax2 = 0;
Vmax3 = 0;
VmaxOut = 0;

for i = 1:length(s1)
    if s1(i) > VAlim
        s1(i)  = VAlim;
    elseif s1(i)<-VAlim
        s1(i) = -VAlim;
    end

    if abs(s1(i))>Vmax1
        Vmax1 = abs(s1(i));
    end

end

for i = 1:length(s2)
    if s2(i) > VAlim
        s2(i)  = VAlim;
    elseif s2(i)<-VAlim
        s2(i) = -VAlim;
    end

    if abs(s2(i))>Vmax2
        Vmax2 = abs(s2(i));
    end

end

for i = 1:length(s3)
    if s3(i) > VAlim
        s3(i)  = VAlim;
    elseif s3(i)<-VAlim
        s3(i) = -VAlim;
    end

    if abs(s3(i))>Vmax3
        Vmax3 = abs(s3(i));
    end

end

% Relatia semnalului de iesire

sOut = -Rn*multn*(s1./(R1*mult1) + s2./(R2*mult2) +s3./(R3*mult3));   % expresia semnalului de iesire


for i = 1:length(sOut)
    if sOut(i) > VAlim
        sOut(i)  = VAlim;
    elseif sOut(i)<-VAlim
        sOut(i) = -VAlim;
    end

    if abs(sOut(i))>VmaxOut
        VmaxOut = abs(sOut(i));
    end
end


% Reprezentarea grafica a semnalelor de intrare/iesire pe un singur plot

p = subplot(223);
if (type1 ==2 || type1 ==3 || type1==4)
    plot(t,s1,'r');
    hold on;
else
    yline(ValMed1,'r','LineWidth',3);       % in cazul in care semnalele introduse sunt doar de tip continuu, reprezentarea grafica difera.
    hold on;
end

if (type2 ==2 || type2 ==3 || type2==4)
    plot(t,s2,'g');
    hold on;
else
    yline(ValMed2,'g','LineWidth',3);
    hold on;
end

if (type3 ==2 || type3 ==3 || type3==4)
    plot(t,s3,'k');
    hold on;
else
    yline(ValMed3,'k','LineWidth',3);
    hold on;
end


if(type1 == 1 && type2 == 1 && type3 ==1)
    valMedOut = -((Rn*multn)*ValMed1/(R1*mult1) + (Rn*multn)*ValMed2/(R2*mult2) + (Rn*multn)*ValMed3/(R3*mult3));
    if valMedOut > VAlim
        valMedOut = VAlim;
    elseif valMedOut < -VAlim
        valMedOut =  -VAlim;
    end

    yline(valMedOut,'b','LineWidth',3);
    hold on;
    grid on;
else
    plot(t,sOut,'b','LineWidth',2);
    hold on;
    grid on;
end
title('Reprezentarea grafica','FontAngle','italic','FontSize',15)
xlabel('timp [s]','FontWeight','bold','FontSize',13);
ylabel('Amplitudine [V]','FontWeight','bold','FontSize',13);
legend('In I','In II','In III','Out');

% Rescrierea variabilelor amplitudinilor semnalelor de intrare cu 0 la
% semnalele cuntinue

if type1 ==1
    Ampl1 =0;
end

if type2 ==1
    Ampl2 =0;
end

if type3 ==1
    Ampl3 =0;
end

% determinarea Slew Rate-ului necesar si limitarea datorata de acesta

slewMin1 = 2* pi * Vmax1 * f1;

if slewMin1 > SR*100000
    f1 = ((SR*100000)./(2*pi*Vmax1))-1;
    close all;
    delete(p);
    interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn);
end

slewMin2 = 2* pi * Vmax2 * f2;

if slewMin2 > SR*100000
    f2 = ((SR*100000)./(2*pi*Vmax2))-1;
    close all;
    delete(p);
    interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn);
end

slewMin3 = 2* pi * Vmax3 * f3;

if slewMin3 > SR*100000
    f3 = ((SR*100000)./(2*pi*Vmax3))-1;
    close all;
    delete(p);
    interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn);
end

% limitarea curentului maxim
% singura metoda de a reduce curentul de iesire este de a scadea
% amplificarea. Astfel se vor egala rezistentele R1, R2, R3 si Rn cu o
% valoare a rezistentei minime pentru a nu depasi limita AO.

Iout = VmaxOut/(Rn*multn);
if (Iout > IMAX/1000)

    Rezmin = double(VmaxOut./(IMAX/1000));
    newxR=0;
    if (Rezmin>0 && Rezmin <910)
        newxR = 1;
    elseif Rezmin < 910000
        newxR =2;
        Rezmin = Rezmin/1000;
    else
        newxR =3;
        Rezmin = Rezmin/1000000;
    end
    newR = rezistenteSTDHigh(newxR,Rezmin);

    Rn = newR;
    R1 = newR;
    R2 = newR;
    R3 = newR;
    xR1 = newxR;
    xR2 = newxR;
    xR3 = newxR;
    xRn = newxR;
    close;
    interfataAO_Sumator(f1,f2,f3,ValMed1,ValMed2,ValMed3,Ampl1,Ampl2,Ampl3,R1,R2,R3,Rn,VAlim,type1,type2,type3,SR,IMAX,xR1,xR2,xR3,xRn);
end


% meniul pentru documentatie
dOc=uimenu('Label','Documentatie');
uimenu(dOc,'Label','Titlul si Autorul Proiectului','Callback','winopen TitluProiect.htm');
uimenu(dOc,'Label','Scopul Lucrarii','Callback','winopen Scopul_Proiectului.htm');
uimenu(dOc,'Label','Ecuatii si Forumule','Callback','winopen ecuatii_forumule.htm');
uimenu(dOc,'Label','Prezentarea interfetei grafice','Callback','winopen Prezentare_interfataGrafica.htm');
uimenu(dOc,'Label','Prezentare PowerPoint','Callback','winopen ppw.pptx');

end


